// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lboqahwardtgidzcgxjl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imxib3FhaHdhcmR0Z2lkemNneGpsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEwMjQ2MDgsImV4cCI6MjA2NjYwMDYwOH0.z6SKjbCyZCtd-bMxLSveVVBvDDpqDaNbzQSy0lREPgw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);